---
- name: Prepare Virt Environments config path
  hosts: localhost
  tasks:
    - name: Create logs path
      file: 
        path: /root/upgrade-venvs/logs
        state: directory

    - name: Create logs path for keystone
      file: 
        path: /root/upgrade-venvs/logs/keystone
        state: directory

    - name: Create logs path for glance
      file: 
        path: /root/upgrade-venvs/logs/glance
        state: directory

    - name: Create logs path for cinder
      file: 
        path: /root/upgrade-venvs/logs/cinder
        state: directory

    - name: Create logs path for nova
      file: 
        path: /root/upgrade-venvs/logs/nova
        state: directory

    - name: Create logs path for neutron
      file: 
        path: /root/upgrade-venvs/logs/neutron
        state: directory

    - name: Create logs path for designate
      file: 
        path: /root/upgrade-venvs/logs/designate
        state: directory

    - name: Create logs path for heat
      file: 
        path: /root/upgrade-venvs/logs/heat
        state: directory

    - name: Create config path
      file: 
        path: /root/upgrade-venvs/configs
        state: directory

- name: Get config files from keystone container
  hosts: keystone_all[0]
  tasks:
    - synchronize:  
        src: /etc/keystone 
        dest: /root/upgrade-venvs/configs
        mode: pull
        recursive: true
        rsync_opts:
          - "-a"

- name: Get config files from glance container
  hosts: glance_all[0]
  tasks:
    - synchronize:  
        src: /etc/glance 
        dest: /root/upgrade-venvs/configs
        mode: pull
        recursive: true
        rsync_opts:
          - "-a"

- name: Get config files from cinder container
  ignore_errors: true
  hosts: cinder_all[0]
  tasks:
    - synchronize:  
        src: /etc/cinder 
        dest: /root/upgrade-venvs/configs
        mode: pull
        recursive: true
        rsync_opts:
          - "-a"

- name: Get config files from nova container
  hosts: nova_all[0]
  tasks:
    - synchronize:  
        src: /etc/nova 
        dest: /root/upgrade-venvs/configs
        mode: pull
        recursive: true
        rsync_opts:
          - "-a"

- name: Get config files from neutron container
  hosts: neutron_server_container[0]
  tasks:
    - synchronize:  
        src: /etc/neutron 
        dest: /root/upgrade-venvs/configs
        mode: pull
        recursive: true
        rsync_opts:
          - "-a"

#- name: Get config files from designate container
#  hosts: designate_all[0]
#  tasks:
#    - synchronize:  
#        src: /etc/designate 
#        dest: /root/upgrade-venvs/configs
#        mode: pull
#        recursive: true
#        rsync_opts:
#          - "-a"

- name: Get config files from heat container
  hosts: heat_all[0]
  tasks:
    - synchronize:  
        src: /etc/heat 
        dest: /root/upgrade-venvs/configs
        mode: pull
        recursive: true
        rsync_opts:
          - "-a"

- name: Verify configs and logs are in place
  hosts: localhost
  tasks:
    - name: remove directory if it exists
      file:
        path: /etc/keystone
        state: absent

    - name: Create symbolic link 
      file:
        src: /root/upgrade-venvs/configs/keystone
        dest: /etc/keystone
        state: link

    - name: Create symbolic link 
      file:
        src: /root/upgrade-venvs/logs/keystone
        dest: /var/log/keystone
        state: link

    - name: remove directory if it exists
      file:
        path: /etc/glance
        state: absent

    - name: Create symbolic link 
      file:
        src: /root/upgrade-venvs/configs/glance
        dest: /etc/glance
        state: link

    - name: Create symbolic link 
      file:
        src: /root/upgrade-venvs/logs/glance
        dest: /var/log/glance
        state: link

    - name: remove directory if it exists
      file:
        path: /etc/cinder
        state: absent

    - name: Create symbolic link 
      file:
        src: /root/upgrade-venvs/configs/cinder
        dest: /etc/cinder
        state: link

    - name: Create symbolic link 
      file:
        src: /root/upgrade-venvs/logs/cinder
        dest: /var/log/cinder
        state: link

    - name: remove directory if it exists
      file:
        path: /etc/nova
        state: absent

    - name: Create symbolic link 
      file:
        src: /root/upgrade-venvs/configs/nova
        dest: /etc/nova
        state: link

    - name: Create symbolic link 
      file:
        src: /root/upgrade-venvs/logs/nova
        dest: /var/log/nova
        state: link

    - name: remove directory if it exists
      file:
        path: /etc/neutron
        state: absent

    - name: Create symbolic link 
      file:
        src: /root/upgrade-venvs/configs/neutron
        dest: /etc/neutron
        state: link

    - name: Create symbolic link 
      file:
        src: /root/upgrade-venvs/logs/neutron
        dest: /var/log/neutron
        state: link

#    - name: remove directory if it exists
#      file:
#        path: /etc/designate
#        state: absent
  
#    - name: Create symbolic link 
#      file:
#        src: /root/upgrade-venvs/configs/designate
#        dest: /etc/designate
#        state: link

#    - name: Create symbolic link 
#      file:
#        src: /root/upgrade-venvs/logs/designate
#        dest: /var/log/designate
#        state: link

    - name: remove directory if it exists
      file:
        path: /etc/heat
        state: absent
  
    - name: Create symbolic link 
      file:
        src: /root/upgrade-venvs/configs/heat
        dest: /etc/heat
        state: link

    - name: Create symbolic link 
      file:
        src: /root/upgrade-venvs/logs/heat
        dest: /var/log/heat
        state: link
