---

- hosts: localhost
  connection: local
  become: yes
  gather_facts: no
  tasks:
    - name: Remove the inventory entries for the deleted containers
      command: >-
        /opt/openstack-ansible/scripts/inventory-manage.py -r {{ item }}
      with_items: "{{ groups['nova_api_metadata_container'] +
                      groups['nova_api_os_compute_container'] +
                      groups['nova_api_placement_container'] |default([]) +
                      groups['nova_conductor_container'] +
                      groups['nova_console_container'] +
                      groups['nova_scheduler_container'] }}"
