---

- name: Prepare Virt Environments
  hosts: localhost
  tasks:
    - name: Perform train Keystone DB sync
      shell: "/root/upgrade-venvs/train/bin/keystone-manage --nouse-journal --log-file=/var/log/keystone/keystone.log db_sync"

    - name: Perform train glance DB sync
      shell: "/root/upgrade-venvs/train/bin/glance-manage db sync"

    - name: Perform train cinder DB sync
      shell: "/root/upgrade-venvs/train/bin/cinder-manage --nouse-journal --log-file=/var/log/cinder/cinder.log db sync"

    - name: Perform online data migrations train cinder
      shell: "/root/upgrade-venvs/train/bin/cinder-manage --nouse-journal --log-file=/var/log/cinder/cinder.log db online_data_migrations"

    - name: Perform train Nova API DB sync
      shell: "/root/upgrade-venvs/train/bin/nova-manage --nouse-journal --log-file=/var/log/nova/nova.log api_db sync"

    - name: Perform train Nova DB sync
      shell: "/root/upgrade-venvs/train/bin/nova-manage --nouse-journal --log-file=/var/log/nova/nova.log db sync"

    - name: Perform train online data migrations
      shell: "/root/upgrade-venvs/train/bin/nova-manage --nouse-journal --log-file=/var/log/nova/nova.log db online_data_migrations"

    - name: Perform train neutron DB upgrade
      shell: "/root/upgrade-venvs/train/bin/neutron-db-manage upgrade $(neutron-db-manage branches | grep expand | awk '{print $2}')"
      #      shell: "/root/upgrade-venvs/train/bin/neutron-db-manage upgrade head"

      #    - name: Perform train neutron DB offline migrations
      #      shell: "/root/upgrade-venvs/train/bin/neutron-db-manage has_offline_migrations"

      #    - name: Perform train designate DB upgrade
      #      shell: "/root/upgrade-venvs/train/bin/designate-manage database sync"
      #      when: groups['designate_all'] | default('') |length > 0

      #    - name: Perform train heat DB upgrade
      #      shell: "/root/upgrade-venvs/train/bin/heat-manage db_sync"
