---

- name: Prepare Virt Environments
  hosts: localhost
  tasks:
    - name: Perform queens Keystone DB sync
      shell: "/root/upgrade-venvs/queens/bin/keystone-manage db_sync"

    - name: Perform queens glance DB sync
      shell: "/root/upgrade-venvs/queens/bin/glance-manage db sync"

    - name: Perform queens cinder DB sync
      shell: "/root/upgrade-venvs/queens/bin/cinder-manage db sync"

    - name: Perform online data migrations queens cinder
      shell: "/root/upgrade-venvs/queens/bin/cinder-manage db online_data_migrations"

    - name: Perform queens Nova API DB sync
      shell: "/root/upgrade-venvs/queens/bin/nova-manage api_db sync"

    - name: Perform queens Nova DB sync
      shell: "/root/upgrade-venvs/queens/bin/nova-manage db sync"

    - name: Perform queens online data migrations
      shell: "/root/upgrade-venvs/queens/bin/nova-manage db online_data_migrations"

    - name: Perform queens neutron DB upgrade
      shell: "/root/upgrade-venvs/queens/bin/neutron-db-manage upgrade --expand"

    - name: Perform queens neutron DB offline migrations
      shell: "/root/upgrade-venvs/queens/bin/neutron-db-manage has_offline_migrations"

    - name: Perform queens designate DB upgrade
      shell: "/root/upgrade-venvs/queens/bin/designate-manage database sync"

    - name: Perform queens designate pool update
      shell: "/root/upgrade-venvs/queens/bin/designate-manage pool update"

    - name: Perform queens heat DB upgrade
      shell: "/root/upgrade-venvs/queens/bin/heat-manage db_sync"
