---

- name: Prepare Virt Environments
  hosts: localhost
  tasks:
    - name: Perform pike Keystone DB sync
      shell: "/root/upgrade-venvs/pike/bin/keystone-manage db_sync"

    - name: Perform pike glance DB sync
      shell: "/root/upgrade-venvs/pike/bin/glance-manage db sync"

    - name: Perform pike cinder DB sync
      shell: "/root/upgrade-venvs/pike/bin/cinder-manage db sync"

    - name: Perform online data migrations pike cinder
      shell: "/root/upgrade-venvs/pike/bin/cinder-manage db online_data_migrations"

    - name: Perform pike Nova API DB sync
      shell: "/root/upgrade-venvs/pike/bin/nova-manage api_db sync"

    - name: Perform pike Nova DB sync
      shell: "/root/upgrade-venvs/pike/bin/nova-manage db sync"

    - name: Perform pike online data migrations
      shell: "/root/upgrade-venvs/pike/bin/nova-manage db online_data_migrations"

    - name: Perform pike neutron DB upgrade
      shell: "/root/upgrade-venvs/pike/bin/neutron-db-manage upgrade --expand"

    - name: Perform pike neutron DB offline migrations
      shell: "/root/upgrade-venvs/pike/bin/neutron-db-manage has_offline_migrations"

    - name: Perform pike designate DB upgrade
      shell: "/root/upgrade-venvs/pike/bin/designate-manage database sync"

    - name: Perform pike heat DB upgrade
      shell: "/root/upgrade-venvs/pike/bin/heat-manage db_sync"
